stages:
  - stage: CheckDependencies
    displayName: 'Dependency Security Scan'
    jobs:
      - job: AuditDependencies
        displayName: 'NPM Audit & Snyk Scan'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'

          - script: |
              cd src
              npm ci
            displayName: 'Install dependencies'

          - script: |
              cd src
              npm audit --audit-level=moderate --json > npm-audit-results.json || true
              echo "NPM audit completed (non-blocking for now)"
            displayName: 'Run NPM audit'
            continueOnError: true

          # TODO: Configure Snyk service connection and uncomment
          # - task: SnykSecurityScan@1
          #   inputs:
          #     serviceConnectionEndpoint: '$(snykServiceConnection)'
          #     testType: 'app'
          #     targetFile: 'src/package.json'
          #     monitorWhen: 'always'
          #     failOnIssues: false  # Set to true when ready for enforcement
          #     projectName: 'orchestrix-ui-src'
          #     additionalArguments: '--severity-threshold=medium --json-file-output=snyk-results.json'

          # TODO: Enable Trivy filesystem scan when Docker is available
          # - script: |
          #     docker run --rm -v $(System.DefaultWorkingDirectory):/project aquasec/trivy:latest fs --security-checks vuln --format sarif --output /project/trivy-results.sarif /project/src || true
          #   displayName: 'Run Trivy filesystem scan'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'src/npm-audit-results.json'
              ArtifactName: 'dependency-scan-results'
            condition: always()