stages:
  - stage: CheckCode
    displayName: 'Code Quality & Testing'
    jobs:
      - job: LintTypeCheckTest
        displayName: 'Lint, Type Check & Test'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'

          - script: |
              cd src
              npm ci
            displayName: 'Install dependencies'

          - script: |
              cd src
              npm run lint
            displayName: 'Run ESLint (fail fast)'

          - script: |
              cd src
              npx tsc --noEmit
            displayName: 'TypeScript type check'

          - script: |
              cd src
              npm run test:unit
            displayName: 'Run unit tests'
            continueOnError: true

          - script: |
              cd src
              npm run test:coverage
            displayName: 'Generate coverage report'
            continueOnError: true

          # TODO: Enable SARIF upload when service connections are configured
          # - task: PublishTestResults@2
          #   inputs:
          #     testResultsFormat: 'JUnit'
          #     testResultsFiles: 'src/test-results.xml'
          #   condition: always()

          # TODO: Enable coverage publishing
          # - task: PublishCodeCoverageResults@1
          #   inputs:
          #     codeCoverageTool: 'Cobertura'
          #     summaryFileLocation: 'src/coverage/cobertura-coverage.xml'
          #   condition: always()