stages:
  - stage: BuildPackages
    displayName: 'Build StencilJS Components & Storybook'
    jobs:
      - job: BuildStencilComponents
        displayName: 'Build Components'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'

          - script: |
              cd packages/components
              npm ci
            displayName: 'Install component dependencies'

          - script: |
              cd packages/components
              npm run build
            displayName: 'Build StencilJS components'
            continueOnError: true

          - script: |
              cd packages/components
              npm run test || true
            displayName: 'Test StencilJS components'
            continueOnError: true

      - job: BuildStorybook
        displayName: 'Build Storybook'
        dependsOn: BuildStencilComponents
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'

          - script: |
              cd packages/storybook
              npm ci || true
            displayName: 'Install Storybook dependencies'
            continueOnError: true

          - script: |
              cd packages/storybook
              npm run build || true
            displayName: 'Build Storybook'
            continueOnError: true

          # TODO: Add visual regression testing when configured
          # - script: |
          #     cd packages/storybook
          #     npm run test:visual || true
          #   displayName: 'Run visual regression tests'