# Package building: Stencil components, Storybook, React wrappers
stages:
  - stage: PackagesBuild
    displayName: 'Build Packages'
    jobs:
      - job: BuildStencil
        displayName: 'Build Stencil Components'
        pool:
          vmImage: 'ubuntu-latest'
        
        steps:
          - task: NodeTool@0
            displayName: 'Setup Node.js 20'
            inputs:
              versionSpec: '20'
          
          # Install Stencil dependencies
          - script: |
              cd packages/components
              npm install
            displayName: 'Install Stencil dependencies'
          
          # Build Stencil components
          - script: |
              cd packages/components
              npm run build
            displayName: 'Build Stencil components'
          
          # Publish Stencil artifacts
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Stencil build artifacts'
            inputs:
              pathToPublish: 'packages/components/dist'
              artifactName: 'stencil-components'
          
      - job: BuildStorybook
        displayName: 'Build Storybook'
        dependsOn: BuildStencil
        pool:
          vmImage: 'ubuntu-latest'
        
        steps:
          - task: NodeTool@0
            displayName: 'Setup Node.js 20'
            inputs:
              versionSpec: '20'
          
          # Install Storybook dependencies
          - script: |
              cd packages/storybook
              npm install
            displayName: 'Install Storybook dependencies'
          
          # Build Storybook static site
          - script: |
              cd packages/storybook
              npm run build-storybook
            displayName: 'Build Storybook'
          
          # Publish Storybook artifacts
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Storybook artifacts'
            inputs:
              pathToPublish: 'packages/storybook/storybook-static'
              artifactName: 'storybook-static'
      
      - job: BuildReactWrappers
        displayName: 'Build React Wrappers'
        dependsOn: BuildStencil
        pool:
          vmImage: 'ubuntu-latest'
        
        steps:
          - task: NodeTool@0
            displayName: 'Setup Node.js 20'
            inputs:
              versionSpec: '20'
          
          # Download Stencil artifacts to use as dependency
          - task: DownloadBuildArtifacts@0
            displayName: 'Download Stencil components'
            inputs:
              artifactName: 'stencil-components'
              downloadPath: '$(System.ArtifactsDirectory)'
          
          # Install React wrapper dependencies
          - script: |
              cd packages/react-wrappers
              npm install
            displayName: 'Install React wrapper dependencies'
          
          # Build React wrappers
          - script: |
              cd packages/react-wrappers
              npm run build
            displayName: 'Build React wrappers'
          
          # Publish React wrapper artifacts
          - task: PublishBuildArtifacts@1
            displayName: 'Publish React wrapper artifacts'
            inputs:
              pathToPublish: 'packages/react-wrappers/dist'
              artifactName: 'react-wrappers'
      
      - job: IntegrationTest
        displayName: 'Integration Tests'
        dependsOn: 
          - BuildStencil
          - BuildStorybook
          - BuildReactWrappers
        pool:
          vmImage: 'ubuntu-latest'
        
        steps:
          - task: NodeTool@0
            displayName: 'Setup Node.js 20'
            inputs:
              versionSpec: '20'
          
          - script: |
              cd src
              npm ci
            displayName: 'Install main app dependencies'
          
          # Run integration tests (placeholder)
          - script: |
              cd src
              npm run test:integration || echo "##[warning]No integration tests implemented yet"
            displayName: 'Run integration tests'
            continueOnError: true