name: Check Infra

on:
  workflow_dispatch:

jobs:
  check-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Bicep (via Azure CLI action)
        uses: azure/cli@v1
        with:
          inlineScript: |
            az --version
            az bicep build --file infra/main.bicep --stdout
