name: Check Dependencies

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: {}

jobs:
  check-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd src
          npm ci
      - name: Run npm audit
        run: |
          cd src
          npm audit --audit-level=moderate || true
